# Generated by Django 4.2.1 on 2023-12-12 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_alter_empresa_nome'),
        ('servicos', '0001_initial'),
        ('clientes', '0003_rename_nome_cliente_cliente_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrdem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_unitario_na_ordem', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sub_total_item', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.servico')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordens.ordem')),
            ],
        ),
    ]
