# Generated by Django 4.2.1 on 2023-12-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemordem',
            old_name='venda',
            new_name='ordem',
        ),
    ]
