# Generated by Django 4.2.1 on 2023-12-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0003_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ordens.status'),
        ),
    ]
