# Generated by Django 4.2.1 on 2023-06-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_itemvenda_empresa_venda_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvenda',
            name='empresa',
        ),
    ]
