# Generated by Django 4.2.1 on 2023-06-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_itemvenda_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvenda',
            name='empresa',
        ),
    ]
