# Generated by Django 4.2.1 on 2023-06-13 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_venda_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='valor_total',
        ),
    ]
