# Generated by Django 4.2.1 on 2023-09-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0011_venda_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_recebimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
