# Generated by Django 4.2.1 on 2023-09-29 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0014_alter_itemvenda_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendas.venda'),
        ),
    ]
