# Generated by Django 4.2.1 on 2023-12-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0015_alter_itemvenda_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='valor_unitario_na_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
