# Generated by Django 4.2.1 on 2023-12-11 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0016_itemvenda_valor_unitario_na_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='sub_total_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_de_venda', to='vendas.venda'),
        ),
    ]
