# Generated by Django 4.2.1 on 2023-12-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0017_itemvenda_sub_total_item_alter_itemvenda_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
