# Generated by Django 4.2.1 on 2023-12-12 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0019_alter_itemvenda_sub_total_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_de_venda', to='vendas.venda'),
        ),
    ]
