# Generated by Django 4.2.1 on 2023-12-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0022_alter_itemvenda_venda_alter_venda_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='sub_total_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
