# Generated by Django 4.2.1 on 2023-09-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='nome',
            field=models.CharField(max_length=80),
        ),
    ]
