# Generated by Django 4.2.1 on 2023-06-12 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nome_cliente',
            new_name='nome',
        ),
    ]
