# Generated by Django 4.2.1 on 2023-06-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_rename_produtos_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
