# Generated by Django 4.2.1 on 2023-06-11 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_valor_unitario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='nome_produto',
            new_name='nome',
        ),
    ]
