# Generated by Django 4.2.1 on 2023-06-12 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_fornecedor_email_fornecedor_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedor',
            old_name='nome_fornecedor',
            new_name='nome',
        ),
    ]
