# Generated by Django 4.2.1 on 2023-06-09 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('empregados', '0003_alter_empregado_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='empregado',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa'),
            preserve_default=False,
        ),
    ]
