# Generated by Django 4.2.1 on 2023-06-11 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empregados', '0004_empregado_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregado',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
