# Generated by Django 4.2.1 on 2023-12-13 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0006_alter_categoria_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='user',
        ),
    ]
